# Generated by Django 5.0.3 on 2024-04-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='brawl_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
