# Generated by Django 4.2.11 on 2024-05-01 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tracker_app.group'),
        ),
    ]
